### ISSUE TITLE
error when loading

### ISSUE THREAD

**Issue by tehceh** [intrntbrn/smart_borders#1]
hoping for some help-- i'm running the default theme on awesome 4.3, i've added the require line per README.md, and get this error--

```
smart_borders/init.lua:198: attempt to call a nil value (method 'activate')
```

i'm not super familiar with lua-- i presume function(c) is being called, that there is an expectation that it has a method "activate", but not sure what is/isn't being passed.

p.s. your screencap/gif is amazing. in awe of your curses prowess-- lolcat and nvim are now installed.

**Comment by intrntbrn** [comment]
Please update and let me know if it's fixed.

**Comment by tehceh** [comment]
Yes, it is-- I get another error now though

```
/usr/share/awesome/lib/awful/mouse/resize.lua:156: mousegrabber already running
```
Also, I had hoped the config you shared would provide the multi-colored buttons on the border. Is that just an incompatibility? Is there a theme you suggest I pair smart_borders with?

**Comment by intrntbrn** [comment]
The multi-colored buttons are part of `smart_borders` and the example configuration should get you exactly that look (when regular x11 borders are disabled).

I just downgraded to 4.3 and used a default `rc.lua` and i am unable to reproduce your issue.

rc.lua: https://gist.github.com/intrntbrn/f2e1af9e6b67ffa6645cb6c530a25a19

**Comment by tehceh** [comment]
I reinstalled the default rc.lua & theme files, as well as tried your rc.lua, and still no go. Also installed packages for luarocks but not sure that it's being picked up.

Maybe I'll build latest awesome-- here are some other details--

```
> awesome -v
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```
debian bullseye dist files --
system installed rc.lua/theme.lua: https://gist.github.com/tcmeggs/364356d6899ee3127ff5182236ac5fc2

**Comment by tehceh** [comment]
Using your provided rc.lua
(rc.lua: https://gist.github.com/intrntbrn/f2e1af9e6b67ffa6645cb6c530a25a19)

And building an updated deb from source, the problems were resolved.

https://github.com/awesomeWM/awesome
```
Debian-based

sudo apt build-dep awesome
git clone https://github.com/awesomewm/awesome
cd awesome
make package
sudo apt install *.deb
```
```
||/ Name           Version                  Architecture Description
+++-==============-========================-============-=================================
ii  awesome        4.3.0.0~git856-ge7113d71 amd64        A tiling window manager
```
