### ISSUE TITLE
No borders for certain clients

### ISSUE THREAD

**Issue by aberwenig** [intrntbrn/smart_borders#10]
Hi. I have been using smart_borders for some months now and it's great. But there's something I'm missing: for some types of clients (e.g. the "new e-mail" notifier I use) I would like to have no borders at all. I have rules in my rc.lua to specify that, but then smart_borders gets loaded and it overrides the previous per-client settings. Can you suggest a solution?
Thanks!

**Comment by intrntbrn** [comment]
smart_borders is currently ignoring `titlebars_enabled` or `request_no_titlebar` client properties.
Please post your rules.

**Comment by intrntbrn** [comment]
I've just pushed an update. 

`titlebars_enabled` property changes are now handled by smart_borders.

It's now to possible to toggle titlebars dynamically:
```
echo "client.focus.titlebars_enabled = false" | awesome-client
```

Please let me know if the update fixes your issue.

**Comment by aberwenig** [comment]
Hi, thanks for the update. I applied it but I see no difference. This is what happens:

(In my original post I mentioned the "new e-mail" notifier I use, but it's difficult to test with that, so I tested with 'xcalc'.)

If I type 'xcalc' in a terminal to start an 'xcalc' client, it shows up initially with smart_borders. If I use the keyboard shortcut to show the titlebar, the titlebar is shown and the smart_borders are gone. If I use the same keyboard shortcut again, then the titlebar is gone but the smart_borders do not reappear, so the 'xcalc' window is left with no borders at all. This is the state I would like the window to appear in the first place: no borders at all.

The behavior described above is the same on a machine where I did not apply the update, so I don't know what the update does.

I have these lines in my 'rc.lua':

    { rule = { class = "XCalc" },
      properties = { border_width = 0 },
        callback = function (c)
            awful.placement.centered(c, nil)
            awful.titlebar.add(c, { modkey = modkey})
            awful.titlebar.show(c)
        end },

I tried commenting out one or the other or both of the 2 lines with 'titlebar' in them, but I see no change.

Thanks.

**Comment by intrntbrn** [comment]
Please pull the latest update. 
Instead of the `titlebars_enabled` property there is now a `disable_smart_borders` client property. 

If you want to disable smart_borders for a certain client, you just have to set the client property `disable_smart_borders` to true.
You can verify this by running the following command in your terminal:
```
echo "client.focus.disable_smart_borders = true" | awesome-client
```

I've also added an example in `README.md` on how to define rules:
https://github.com/intrntbrn/smart_borders/blob/master/README.md#disable
