### ISSUE TITLE
Smart Borders are Transparent

### ISSUE THREAD

**Issue by chxp82q** [intrntbrn/smart_borders#2]
Hello, 

Thanks for your amazing work! The problem is that no matter how I set the color, the borders are transparent. This also happens even when I use your example configuration. However, the other settings like border width and tooltip do work. The borders are also transparent when I have my compositor turned off.

```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

[Screenshot](https://imgur.com/eyYBa8B.png)

**Comment by intrntbrn** [comment]
That's odd. Have you tried a default `rc.lua`? Try this one: https://gist.github.com/intrntbrn/f2e1af9e6b67ffa6645cb6c530a25a19

**Comment by intrntbrn** [comment]
And what happens if you explicitly set the color to be non-transparent (e.g. `color_focus = "#a9dd9dFF"`)?

**Comment by chxp82q** [comment]
Just tried it, still transparent: [shot](https://imgur.com/vpx2VIl)

I'll try setting it non-transparent.

**Comment by chxp82q** [comment]
So setting it explicitly didn't work, however once I installed the `awesome-git` version it worked.
```
awesome v4.3-858-g49a3859c8 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```
So I guess this doesn't have support for the regular packaged version of awesome on arch?

Here was my old awesome specs:
```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**Comment by intrntbrn** [comment]
Glad to hear. It should work without any issues on 4.3 usually. I tested the module with the regular `awesome` package on arch.

**Comment by aaronclimbs** [comment]
> I tested the module with the regular `awesome` package on arch.

I'm having the same issue described above. Clearly, the package is working properly as the buttons work and I can see the tooltips, but I can't see any borders/button colors. I'm wondering if there were any additional fixes you or @JavaCafe01 implemented in order to fix the transparency issue. 

```shell
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```
I'm sure it's possible that I've customized some part of my rc.lua or theme.lua and it's somehow overriding the plugin values. Happy to attach them if necessary, but I was hoping there was just an easy fix that I'm missing.

Picture: https://imgur.com/a/2DCgfoF

**Comment by intrntbrn** [comment]
Please test without a compositor and [default 4.3 rc.lua](https://gist.github.com/intrntbrn/f2e1af9e6b67ffa6645cb6c530a25a19).

**Comment by aaronclimbs** [comment]
I've killed all `picom` instances and turned on the default `rc.lua` provided. Now, I'm seeing the borders, but they remain transparent. If necessary, I can compile and build `awesomewm git`. I was just trying to avoid installing all of the dependencies.

Picture: https://imgur.com/a/Q3YVK5r

**Comment by intrntbrn** [comment]
I've managed to reproduce the issue. I will look into it.

**Comment by intrntbrn** [comment]
Please let me know if this is fixed now.

**Comment by aaronclimbs** [comment]
Works great. Interesting fix. Thanks!
