### ISSUE TITLE
[Feature Request] Separate Button Position

### ISSUE THREAD

**Issue by chxp82q** [intrntbrn/smart_borders#3]
Just like how each button size can be configured, there should be options for configuring positions of each button separately, unless there is already an implementation and I haven't figured it out yet.

Example: Have the maximize button on the top border to the left, and have the close button on the right border towards the top.

**Comment by intrntbrn** [comment]
It's already possible, but it's more or less a hack.

You can have a separate config for each position by initializing `smart_borders` several times:

```
require("smart_borders") {
    positions = {"top"},
	-- definitions for top borders...
}

require("smart_borders") {
    positions = {"bottom"},
	-- definitions for bottom borders...
}
```
