### ISSUE TITLE
titlebar without borders

### ISSUE THREAD

**Issue by mgabs** [intrntbrn/smart_borders#4]
Hi,
Great work.
I want to a slim titlebar only with no borders.
Is this possible?

**Comment by intrntbrn** [comment]
Like this?
![](https://i.imgur.com/1ZLyKa1.png)

```require("smart_borders") {positions = {"top"}}```

**Comment by mgabs** [comment]
Exactly what i was looking for you.
beautiful work, and kudo on the configurable approach.
