### ISSUE TITLE
Trouble getting started

### ISSUE THREAD

**Issue by mxmilkiib** [intrntbrn/smart_borders#6]
Hi. I've got a [basic config](https://github.com/mxmilkiib/dotfiles/blob/master/awesome/.config/awesome/rc.lua#L43) set up (Debian Buster on an Odroid N2) but I'm not seeing any smart_bars, just the regular titlebar. Might there be something obvious I have missed?

**Comment by intrntbrn** [comment]
Move `require("smart_borders") {positions = {"top"}}` to the very bottom.

**Comment by mxmilkiib** [comment]
Hah, argh, I was sure I had tried that, sorted, thanks :)
