### ISSUE TITLE
change floating window border colour?

### ISSUE THREAD

**Issue by Rockwell1799** [intrntbrn/smart_borders#7]
Hello 
First, thank you for smart_borders its awesome!
Can you tell me please how to change the floating windows border colours? I want to differentiate between tiled and floating windows by their border colours!
Thank you in advance

**Comment by intrntbrn** [comment]
Thank you. At the moment this is not possible, but i will try to support your request. I will look into it this weekend.

**Comment by Rockwell1799** [comment]
Thank you !!

**Comment by intrntbrn** [comment]
I just implemented your request but i don't have time for proper testing. 
Please checkout branch "floatcolor". 

You can specify the color by defining `color_floating` (i also implemented `color_maximized`).

Please let me know if does work properly on your end.

**Comment by Rockwell1799** [comment]
Hello 
I defined color_floating="#ffffff" inside the smart borders code block in my rc.lua, but I did not see any color change between tiled and floating!

**Comment by intrntbrn** [comment]
And you did pull the `floatcolor` git branch? 
```
git pull && git checkout floatcolor
```

What's your awesomewm version?

**Comment by Rockwell1799** [comment]
I'm on awesome-git. Now, it's working! Thank you!
