### ISSUE TITLE
Not an issue, a question re rounded corner values

### ISSUE THREAD

**Issue by alan12345678** [intrntbrn/smart_borders#9]
Hi,

Thanks for a terrific extension. Pls forgive my stupidity... it's not quite clear how I set individual rounded corner values in the init.lua?

I can see that you allow for values on each side, I just can't quite work out the correct syntax.

Many thanks :)

**Comment by intrntbrn** [comment]
There is currently no option to set individual rounded corner values.

However, you might be able to workaround this problem by initializing smart_borders for every position.

```
require("smart_borders") {
    positions = {"top"},
    rounded_corner = 0,
}

require("smart_borders") {
    positions = {"bottom"},
    rounded_corner = 10,
}
```

Let me know if it does work.

**Comment by alan12345678** [comment]
oh! I see. Yes.

However, I fear that as a programmer, this all makes absolutely clear sense to you. As an intelligent person but NOT a coder, I understand exactly the principle - you have correctly picked up on exactly what I thought should happen/how it should be set. But I'm afraid (again) that I'm now bewildered. I can't tell if I set those in my rc.lua, or at the top of your init.lua?

I would like to apply the exact same principle to the border heights too i.e. a dpi(1) for left, right, bottom, but something wider at the top.

So overall, I could set e.g. the "smart_borders" at top e.g. dpi(10) wide, and with some rounded_corner value to suit, while having all other borders much thinner, with a smaller rounded_corner value.

I am busy playing around with various options, but unfortunately it's all guesswork with me. I may stumble upon the correct order of words :)

**Comment by intrntbrn** [comment]
Put the initialization code `require 'smart_borders' = {...}` at the bottom of your `rc.lua`

Or just follow the installation guide.

**Comment by alan12345678** [comment]
thank you again. I looked again and managed to answer my own question.

p.s. I always follow installation instructions. The whole "awesomewm" thing being, of itself, quite a brain-stretch for the n00b.

I should be able to get  this working as desired now. Thanks again for all the help :)
